[reftext="Introduction"]
== 前書き（Introduction）

https://archunit.org[ArchUnit] is a free, simple and extensible library for checking the
architecture of your Java code.
That is, ArchUnit can check dependencies between packages and classes, layers and slices,
check for cyclic dependencies and more. It does so by analyzing given Java bytecode,
importing all classes into a Java code structure.
ArchUnit's main focus is to automatically test architecture and coding rules,
using any plain Java unit testing framework.

https://archunit.org[ArchUnit]はJavaソースコードのアーキテクチャをチェックする、簡潔性と拡張性に優れたフリーなライブラリです。
ArchUnitはパッケージやクラス間の依存関係に加えて、レイヤーやスライス間の依存関係をチェックできます。それ以外に、循環する依存関係もチェックできます。
依存関係のチェックは、Javaソースコードに登場する全てのクラスをインポートしたバイトコードについて行います。
ArchUnitの主な目的は、一般的なユニットテストフレームワークで、アーキテクチャやコーディングルールを自動的にテストすることです。

[reftext="Module Overview"]
=== モジュールの概要（Module Overview）

ArchUnit consists of the following production modules: `archunit`, `archunit-junit4` as well
as `archunit-junit5-api`, `archunit-junit5-engine` and `archunit-junit5-engine-api`.
Also relevant for end users is the `archunit-example` module.

ArchUnitの公開モジュールは `archunit` と、`archunit-junit4` あるいは `archunit-junit5-api`、`archunit-junit5-engine`、`archunit-junit5-engine-api` です。
エンドユーザとしては `archunit-example` モジュールも参考になるでしょう。

[reftext="Module archunit"]
==== archunit モジュール（Module archunit）

This module contains the actual ArchUnit core infrastructure required to write architecture
tests: The `ClassFileImporter`,
the domain objects, as well as the rule syntax infrastructure.

このモジュールはアーキテクチャテストを記述するために必要な ArchUnit の基本部品を含んでいます。
例えば `ClassFileImporter` というドメインオブジェクトや、ルールの文法を定義する部品を含んでいます。

[reftext="Module archunit-junit4"]
==== archunit-junit4 モジュール（Module archunit-junit4）

This module contains the infrastructure to integrate with JUnit 4, in particular
the `ArchUnitRunner` to cache imported classes.

このモジュールは ArchUnit を JUnit 4 へ統合するための部品を含んでいます。
特に `ArchUnitRunner` はインポートしたクラス（のバイトコード）をキャッシュするようになっています。

[reftext="Modules archunit-junit5-*"]
==== archunit-junit5-* モジュール（Modules archunit-junit5-*）

These modules contain the infrastructure to integrate with JUnit 5 and contain the respective
infrastructure to cache imported classes between test runs.
`archunit-junit5-api` contains the user API to write tests with ArchUnit's JUnit 5 support,
`archunit-junit5-engine` contains the runtime engine to run those tests.
`archunit-junit5-engine-api` contains API code for tools that want more detailed control
over running ArchUnit JUnit 5 tests, in particular a `FieldSelector` which can be used to
instruct the `ArchUnitTestEngine` to run a specific rule field (compare <<JUnit 4 & 5 Support>>).

これらのモジュールは ArchUnit を JUnit 5 へ統合するための部品を含んでいます。
また、それぞれのテストケースについてインポートしたクラス（のバイトコード）をキャッシュするための部品も含んでいます。
`archunit-junit5-api` は JUnit 5 で ArchUnit のテストを記述するためのユーザ向けAPIを含んでいます。
`archunit-junit5-engine` はテストを実行するランタイムエンジンを含んでいます。
`archunit-junit5-engine-api` はテストツールがより適切に JUnit 5 の ArchUnit テストを制御するためのAPIコードを含んでいます。
例えば、`FieldSelector` は `ArchUnitTestEngine` に特定のルールフィールドだけを実行させることができます。
（ <<JUnit 4 & 5 Support>> とも読み比べてみてください）

[reftext="Module archunit-example"]
==== archunit-example モジュール（Module archunit-example）

This module contains example architecture rules and sample code that violates these rules.
Look here to get inspiration on how to set up rules for your project, or at
https://github.com/TNG/ArchUnit-Examples[ArchUnit-Examples] for the last released version.

このモジュールはアーキテクチャルールの具体例や、ルール違反しているサンプルコードを含んでいます。
このモジュールを見れば、あなたのプロジェクトで整備するルールについてひらめきを得ることができるでしょう。
最新バージョンは https://github.com/TNG/ArchUnit-Examples[ArchUnit-Examples] で参照できます。
